color0 #212630
color1 #fd4663
color2 #8b9ac1
color3 #8c81b1
color4 #a382b0
color5 #acb7d3
color6 #b6afd0
color7 #f2f2f3
color8 #636772
color9 #fd4663
color10 #8b9ac1
color11 #8c81b1
color12 #a382b0
color13 #acb7d3
color14 #b6afd0
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1a1c23
background            #1a1c23
foreground            #f2f2f3
selection_foreground  #afb1b6
selection_background  #212630
active_border_color   #8b9ac1
inactive_border_color #212630
url_color             #8b9ac1

active_tab_foreground   #1b1d22
active_tab_background   #8b9ac1
inactive_tab_foreground #afb1b6
inactive_tab_background #212630
cursor_trail_color      #afb1b6
